org: ravilnagmetov
app: aws-python-http-api-project
service: aws-python-http-api-project

provider:
  name: aws
  runtime: python3.7
  versionFunctions: false
  region: eu-central-1



functions:
  hello:
    handler: hello.hello
    name: hello
    events:
      - httpApi:
          path: /
          method: get
