name: Dev Testing Pipeline

on:
  push:
    branches: [dev]

jobs:
  changes:
    runs-on: ubuntu-20.04
    name: "Changes"
    outputs:
      terraform: ${{ steps.filter.outputs.terraform }}
      serverless: ${{ steps.filter.outputs.serverless }}
      shared: ${{ steps.filter.outputs.shared }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          base: dev
          filters: .github/filters.yml
  shared:
      needs: changes
      if: ${{ needs.changes.outputs.shared == 'true' }}
      runs-on: ubuntu-20.04
      name: "Shared Account Changes"
      steps:
        - uses: actions/github-script@v6
          id: set-result
          if: ${{ always() }}
          with:
            script: return "Hello!"
            result-encoding: string
        - name: Get result
          run: echo "${{steps.set-result.outputs.result}}"


  pytest:
#      needs: [changes]
#      if: ${{ always() && needs.changes.outputs.serverless == 'true' }}
      runs-on: ubuntu-20.04
      name: "Pytest Unit Testing"
      steps:
        - name: "Checkout"
          uses: actions/checkout@v3
  
        - name: "Setup Python 3.7"
          uses: actions/setup-python@v3
          with:
            python-version: "3.12"
        - name: "Check python version"
          run: python3 --version
  
        - name: "Download libxml for xmllsec"
          run: |
            sudo apt-get update
            sudo apt-get install libxml2-dev libxmlsec1-dev libxmlsec1-openssl
  
        - name: "Pip Install testing dependencies"
          run: |
            python -m pip install --upgrade pip
            pip install -r stack/test.requirements.txt
  
        - name: "Run Unit Tests"
          run: pytest
  
